import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Grid,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  FormControlLabel,
  Checkbox,
  Alert,
  CircularProgress,
  IconButton,
  Paper,
  Divider
} from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import SaveIcon from '@mui/icons-material/Save';
import RestartAltIcon from '@mui/icons-material/RestartAlt';
import api from '../services/api.js';

const themeColors = {
  primary: '#1f4fb2',
  secondary: '#2a5ea0',
  lightBlue: '#dbe7fb',
  lighterBlue: '#eaf2fb',
  white: '#ffffff',
  textPrimary: '#333333',
};

const FinancialYearCreate = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const { selectedCompany, user, isAdmin, hasPermission, updateFinancialYear } = useAuth();

  const isEditMode = Boolean(id);

  // Default dates for financial year (e.g., 01-04-2026 to 31-03-2027)
  const defaultStartDate = '2026-04-01';
  const defaultEndDate = '2027-03-31';

  const [formData, setFormData] = useState({
    financial_year: '2026-2027',
    start_date: defaultStartDate,
    end_date: defaultEndDate,
    status: 'Active',
    is_current: true,
    remarks: ''
  });

  const [isAutoGenerated, setIsAutoGenerated] = useState(true);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Check permissions
  const canCreate = isAdmin || hasPermission('Financial Year', 'Create', 'can_create') || hasPermission('User', 'can_create');

  useEffect(() => {
    if (isEditMode) {
      fetchFinancialYearDetail();
    }
  }, [id]);

  // Auto calculate FY string from start_date and end_date
  useEffect(() => {
    if (isAutoGenerated && formData.start_date && formData.end_date) {
      const startYr = formData.start_date.split('-')[0];
      const endYr = formData.end_date.split('-')[0];
      if (startYr && endYr) {
        setFormData(prev => ({
          ...prev,
          financial_year: `${startYr}-${endYr}`
        }));
      }
    }
  }, [formData.start_date, formData.end_date, isAutoGenerated]);

  const fetchFinancialYearDetail = async () => {
    try {
      setLoading(true);
      const data = await api(`/financial-years/detail/${id}`);
      if (data && !data.error) {
        setFormData({
          financial_year: data.financial_year || data.year_name || '',
          start_date: data.start_date || defaultStartDate,
          end_date: data.end_date || defaultEndDate,
          status: data.status || 'Active',
          is_current: data.is_current === 1 || data.is_active === 1,
          remarks: data.remarks || ''
        });
        setIsAutoGenerated(false);
      } else {
        setError(data?.message || 'Failed to load financial year details');
      }
    } catch (err) {
      setError('Error connecting to server');
    } finally {
      setLoading(false);
    }
  };

  const handleDateChange = (field, value) => {
    setFormData(prev => {
      const updated = { ...prev, [field]: value };
      if (field === 'start_date' && value) {
        // Automatically set end_date 1 year later minus 1 day if not set
        const sDate = new Date(value);
        if (!isNaN(sDate.getTime())) {
          const eDate = new Date(sDate);
          eDate.setFullYear(eDate.getFullYear() + 1);
          eDate.setDate(eDate.getDate() - 1);
          const eYear = eDate.getFullYear();
          const eMonth = String(eDate.getMonth() + 1).padStart(2, '0');
          const eDay = String(eDate.getDate()).padStart(2, '0');
          updated.end_date = `${eYear}-${eMonth}-${eDay}`;
        }
      }
      return updated;
    });
  };

  const handleReset = () => {
    if (isEditMode) {
      fetchFinancialYearDetail();
    } else {
      setFormData({
        financial_year: '2026-2027',
        start_date: defaultStartDate,
        end_date: defaultEndDate,
        status: 'Active',
        is_current: true,
        remarks: ''
      });
      setIsAutoGenerated(true);
    }
    setError('');
    setSuccess('');
  };

  const handleSave = async (e) => {
    e.preventDefault();
    if (!formData.financial_year || !formData.start_date || !formData.end_date) {
      setError('Financial Year, Start Date, and End Date are required.');
      return;
    }

    try {
      setSaving(true);
      setError('');
      setSuccess('');

      const payload = {
        company_id: selectedCompany?.id || 1,
        financial_year: formData.financial_year,
        year_name: formData.financial_year,
        start_date: formData.start_date,
        end_date: formData.end_date,
        status: formData.status,
        is_current: formData.is_current ? 1 : 0,
        is_active: formData.is_current ? 1 : 0,
        remarks: formData.remarks,
        created_by: user?.username || 'admin',
        updated_by: user?.username || 'admin'
      };

      const endpoint = isEditMode ? `/financial-years/${id}` : '/financial-years';
      const method = isEditMode ? 'PUT' : 'POST';

      const data = await api(endpoint, {
        method,
        body: payload
      });

      if (data && data.success !== false) {
        setSuccess(data?.message || 'Financial Year saved successfully!');
        
        if (formData.is_current) {
          updateFinancialYear(formData.financial_year);
        }

        setTimeout(() => {
          navigate('/features/financial-year');
        }, 1000);
      } else {
        setError(data?.message || 'Error saving financial year.');
      }
    } catch (err) {
      setError('Error connecting to server.');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', p: 5 }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3, maxWidth: '1000px', margin: '0 auto' }}>
      {/* Page Title & Navigation */}
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
        <IconButton onClick={() => navigate('/features/financial-year')} color="primary">
          <ArrowBackIcon />
        </IconButton>
        <Typography variant="h5" sx={{ fontWeight: 'bold', color: themeColors.primary }}>
          {isEditMode ? 'Edit Financial Year' : 'Financial Year Creation'}
        </Typography>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError('')}>
          {error}
        </Alert>
      )}

      {success && (
        <Alert severity="success" sx={{ mb: 3 }}>
          {success}
        </Alert>
      )}

      {/* Main Section */}
      <Card elevation={3} sx={{ borderRadius: '8px', borderTop: `4px solid ${themeColors.primary}` }}>
        <Box sx={{ p: 2, backgroundColor: themeColors.lighterBlue, borderBottom: '1px solid #cbd5e1' }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 'bold', color: themeColors.primary }}>
            Financial Year Details
          </Typography>
        </Box>

        <CardContent sx={{ p: 3 }}>
          <form onSubmit={handleSave}>
            <Grid container spacing={3}>
              {/* Financial Year */}
              <Grid item xs={12} sm={4}>
                <TextField
                  label="Financial Year"
                  value={formData.financial_year}
                  onChange={(e) => {
                    setIsAutoGenerated(false);
                    setFormData(prev => ({ ...prev, financial_year: e.target.value }));
                  }}
                  fullWidth
                  required
                  size="small"
                  helperText={isAutoGenerated ? "Auto-generated from start & end dates" : "Manual entry"}
                  InputProps={{ style: { fontWeight: 'bold' } }}
                />
              </Grid>

              {/* Start Date */}
              <Grid item xs={12} sm={4}>
                <TextField
                  label="Start Date"
                  type="date"
                  value={formData.start_date}
                  onChange={(e) => handleDateChange('start_date', e.target.value)}
                  fullWidth
                  required
                  size="small"
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>

              {/* End Date */}
              <Grid item xs={12} sm={4}>
                <TextField
                  label="End Date"
                  type="date"
                  value={formData.end_date}
                  onChange={(e) => handleDateChange('end_date', e.target.value)}
                  fullWidth
                  required
                  size="small"
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>

              {/* Status */}
              <Grid item xs={12} sm={6}>
                <FormControl fullWidth size="small">
                  <InputLabel id="status-label">Status</InputLabel>
                  <Select
                    labelId="status-label"
                    label="Status"
                    value={formData.status}
                    onChange={(e) => setFormData(prev => ({ ...prev, status: e.target.value }))}
                  >
                    <MenuItem value="Active">Active</MenuItem>
                    <MenuItem value="Closed">Closed</MenuItem>
                  </Select>
                </FormControl>
              </Grid>

              {/* Current Financial Year */}
              <Grid item xs={12} sm={6}>
                <Paper variant="outlined" sx={{ p: '6px 12px', display: 'flex', alignItems: 'center', height: '100%', borderColor: '#cbd5e1' }}>
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={formData.is_current}
                        onChange={(e) => setFormData(prev => ({ ...prev, is_current: e.target.checked }))}
                        color="primary"
                      />
                    }
                    label={
                      <Typography variant="body2" sx={{ fontWeight: 'bold', color: themeColors.textPrimary }}>
                        Current Financial Year (✓)
                      </Typography>
                    }
                  />
                </Paper>
              </Grid>

              {/* Remarks */}
              <Grid item xs={12}>
                <TextField
                  label="Remarks"
                  value={formData.remarks}
                  onChange={(e) => setFormData(prev => ({ ...prev, remarks: e.target.value }))}
                  fullWidth
                  multiline
                  rows={2}
                  size="small"
                  placeholder="Optional remarks or notes..."
                />
              </Grid>
            </Grid>

            <Divider sx={{ my: 3 }} />

            {/* Action Buttons */}
            <Box sx={{ display: 'flex', justifyContent: 'flex-end', gap: 2 }}>
              <Button
                variant="outlined"
                color="secondary"
                startIcon={<RestartAltIcon />}
                onClick={handleReset}
                disabled={saving}
              >
                Reset
              </Button>
              <Button
                type="submit"
                variant="contained"
                startIcon={<SaveIcon />}
                disabled={saving}
                sx={{ backgroundColor: themeColors.primary, px: 4 }}
              >
                {saving ? 'Saving...' : 'Save'}
              </Button>
            </Box>
          </form>
        </CardContent>
      </Card>
    </Box>
  );
};

export default FinancialYearCreate;
