const chemicalParameters = [
  {
    id: 'protein',
    category: 'chemical',
    parameter: 'Protein (N × 6.25)',
    specification: '',
    unit: '%',
    min: 0,
    max: 20,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'ash',
    category: 'chemical',
    parameter: 'Ash',
    specification: '',
    unit: '%',
    min: 0,
    max: 2.0,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'acid_insoluble_ash',
    category: 'chemical',
    parameter: 'Acid Insoluble Ash',
    specification: '',
    unit: '%',
    min: 0,
    max: 0.5,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'admixture',
    category: 'chemical',
    parameter: 'Admixture',
    specification: '',
    unit: '%',
    min: 0,
    max: 5,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'fat',
    category: 'chemical',
    parameter: 'Fat',
    specification: '',
    unit: '%',
    min: 0,
    max: 2,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
];

export default chemicalParameters;

