const physicalParameters = [
  {
    id: 'moisture',
    category: 'physical',
    parameter: 'Moisture',
    specification: '',
    unit: '%',
    min: 9,
    max: 14,
    method: 'IS 4333',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'weeviled_grains',
    category: 'physical',
    parameter: 'Weeviled Grains',
    specification: '',
    unit: '%',
    min: 0,
    max: 1,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'broken_grains',
    category: 'physical',
    parameter: 'Broken Grains',
    specification: '',
    unit: '%',
    min: 0,
    max: 5,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'foreign_matter',
    category: 'physical',
    parameter: 'Foreign Matter',
    specification: '',
    unit: '%',
    min: 0,
    max: 2,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'damaged_discolored_grains',
    category: 'physical',
    parameter: 'Damaged/Discolored Grains',
    specification: '',
    unit: '%',
    min: 0,
    max: 2,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
  {
    id: 'grain_size_average',
    category: 'physical',
    parameter: 'Grain Size (Average)',
    specification: '',
    unit: 'mm',
    min: 3,
    max: 6,
    method: '',
    result: '',
    status: '',
    remarks: '',
  },
];

export default physicalParameters;

